# -*- coding: utf-8 -*-
"""Copy of A star algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHk5izUF8RA4q0oESDwnm5FWtA2Cmquc
"""

import heapq

def heuristic_func(current,goal):
    count=0
    for i in range(9):
        if current[i]!=0 and current[i]!=goal[i]:
            count=count+1
    return count

def next_states(state):
    next_states_list=[]
    empty=state.index(0)
    row=empty//3
    col=empty%3
    moves=[(-1,0),(1,0),(0,-1),(0,1)]

    for m in moves:
        row_new=row+m[0]
        col_new=col+m[1]
        if 0<=row_new<3 and 0<=col_new<3:
            new_index=row_new*3+col_new
            new_state=list(state)
            new_state[empty],new_state[new_index]=new_state[new_index],new_state[empty]
            next_states_list.append(tuple(new_state))
    return next_states_list

def a_star(start,goal):
    open_list=[]
    heapq.heappush(open_list,(0,start))
    path_cost={start:0}
    parent={start:None}
    visited=set()

    while open_list:
        _,current=heapq.heappop(open_list)

        if current==goal:
            path=[]
            while current is not None:
                path.append(current)
                current=parent[current]
            return path[::-1]

        visited.add(current)

        for next_state in next_states(current):
            if next_state in visited:
                continue

            new_cost=path_cost[current]+1

            if next_state not in path_cost or new_cost<path_cost[next_state]:
                path_cost[next_state]=new_cost
                priority=new_cost+heuristic_func(next_state,goal)
                heapq.heappush(open_list,(priority,next_state))
                parent[next_state]=current

    return None


print("Enter initial state (put 0 in place of space)")
numbers=input().split()
int_numbers=[]
for x in numbers:
    int_numbers.append(int(x))
initial_state=tuple(int_numbers)

print("Enter goal state (put 0 in place of space)")
nums=input().split()
nums_tup=[]
for x in nums:
    nums_tup.append(int(x))
goal_state=tuple(nums_tup)

soln=a_star(initial_state,goal_state)

if soln:
    print("\nSolved in",len(soln)-1,"steps\n")
    for step in soln:
        print(step)
else:
    print("No solution found")