# -*- coding: utf-8 -*-
"""csp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ga-zESzIncwoE7uMvVCxVSkLGQKe-6n
"""

import itertools
def csp_soln():
    letters=('S','E','N','D','M','O','R','Y')
    digits=range(10)
    countp=0
    for p in itertools.permutations(digits,len(letters)):
        countp+= 1
        s,e,n,d,m,o,r,y=p
        if s==0 or m==0:
            continue
        send=s*1000 + e*100 + n*10 + d
        more=m*1000 + o*100 + r*10 + e
        money=m*10000 + o*1000 + n*100 + e* 10 + y

        if send+ more==money:
            print("No. of combinations it took:",countp)
            return {'S':s, 'E':e, 'N':n, 'D':d, 'M':m, 'O':o, 'R':r, 'Y':y}

solution=csp_soln()
if solution:
    print(solution)
else:
    print("No solution found")