# -*- coding: utf-8 -*-
"""TSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wG6HMyScvmILQNDC1SAYuprZJ8cY8rm2
"""

import random

def main():
    n=int(input("Enter number of cities: "))
    matrix=[]
    print("Enter distance matrix:")
    for _ in range(n):
        row=input().split()
        nums=[]
        for v in row:
            nums.append(int(v))
        matrix.append(nums)

    restarts=int(input("Enter random restarts: "))
    route,dist=hillClimbRestart(matrix,restarts)
    print("Best route:",route)
    print("Route length:",dist)

def hillClimbRestart(matrix,restarts):
    bestRoute=None
    bestDist=float("inf")
    for _ in range(restarts):
        route,dist=hillClimb(matrix)
        if dist<bestDist:
            bestRoute,bestDist=route,dist
    return bestRoute,bestDist

def hillClimb(matrix):
    route=randomRoute(matrix)
    dist=routeLen(matrix,route)
    while True:
        neighbours=getNeighbours(route)
        best,bestDist=getBestNeighbour(matrix,neighbours)
        if bestDist<dist:
            route,dist=best,bestDist
        else:
            break
    return route,dist

def randomRoute(matrix):
    route=list(range(len(matrix)))
    random.shuffle(route)
    return route

def routeLen(matrix,route):
    total=0
    for i in range(len(route)):
        total+=matrix[route[i]][route[(i+1)%len(route)]]
    return total

def getNeighbours(route):
    neighbours=[]
    for i in range(len(route)):
        for j in range(i+1,len(route)):
            neighbour=route[:]
            neighbour[i],neighbour[j]=neighbour[j],neighbour[i]
            neighbours.append(neighbour)
    return neighbours

def getBestNeighbour(matrix,neighbours):
    best=neighbours[0]
    bestDist=routeLen(matrix,best)
    for route in neighbours:
        d=routeLen(matrix,route)
        if d<bestDist:
            best,bestDist=route,d
    return best,bestDist

if __name__=="__main__":
    main()